Repository ridhambhat/SlateVim, pull requests merged in 2021-02, with the labels that each got.

#10 Debug `yy`, `dd`, and modularized code slightly
  public/manifest.json
  src/App.js
  src/components/Header.js
  src/components/InsertEditor.js
  src/components/NormalEditor.js
  src/styles/tailwindStyles.js
  src/utils/cursorMethods.js
  src/utils/textEditingMethods.js
  src/utils/variables.js
Labels: priority.High, type.Bug, type.Enhancement, type.Task

#16 Almost all Normal Mode commands (except `j`, `k`), AWS Amplify integration
  .gitignore
  .graphqlconfig.yml
  amplify/.config/project-config.json
  amplify/README.md
  amplify/backend/api/slatevim/parameters.json
  amplify/backend/api/slatevim/schema.graphql
  amplify/backend/api/slatevim/stacks/CustomResources.json
  amplify/backend/api/slatevim/transform.conf.json
  amplify/backend/backend-config.json
  amplify/backend/tags.json
  amplify/cli.json
  amplify/team-provider-info.json
  package.json
  public/manifest.json
  src/App.js
  src/components/CombinedEditor.js
  src/components/InsertEditor.js
  src/components/NormalEditor.js
  src/components/SyncingEditor.js
  src/graphql/mutations.js
  src/graphql/queries.js
  src/graphql/schema.json
  src/graphql/subscriptions.js
  src/styles/tailwindStyles.js
  src/utils/dataMethods.js
  src/utils/variables.js
  yarn.lock
Labels: priority.High, severity.High, type.Enhancement, type.Task

#19 Improve UI
  amplify/backend/backend-config.json
  amplify/backend/hosting/amplifyhosting/amplifyhosting-template.json
  amplify/team-provider-info.json
  public/icons/android-chrome-192x192.png
  public/icons/android-chrome-512x512.png
  public/icons/apple-touch-icon.png
  public/icons/browserconfig.xml
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon.ico
  public/icons/mstile-144x144.png
  public/icons/mstile-150x150.png
  public/icons/mstile-310x150.png
  public/icons/mstile-310x310.png
  public/icons/mstile-70x70.png
  public/icons/safari-pinned-tab.svg
  public/icons/site.webmanifest
  public/index.html
  public/manifest.json
  src/App.js
  src/assets/images/logo.png
  src/components/CombinedEditor.js
  src/components/Header.js
  src/components/Home.js
  src/components/InsertEditor.js
  src/components/NavBar.js
  src/components/NormalEditor.js
  src/components/SyncingEditor.js
  src/styles/tailwindStyles.js
  src/utils/variables.js
Labels: priority.Medium, type.Enhancement

#21 Updated the readme
  README.md
Labels: priority.Medium, type.Documentation, type.Enhancement

#22 Tweak save functionality and add new d- and c- commands
  src/components/CombinedEditor.js
  src/components/Header.js
  src/components/InsertEditor.js
  src/components/NormalEditor.js
Labels: priority.Medium, severity.Medium, type.Enhancement
